spring:
  application:
    name: export-aggregation-service
  profiles:
    active: dev
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      properties:
         schema.registry.url: http://localhost:8081
         username: <username-key>
         password: <password-secret-key>
         topic.pspecs: burraq.product-specifications-service.specifications
         topic.tas: translation-service
         topic.bacs: barcode-service
         topic.pcs: product-code-service
         topic.pas: product-accessory-service
         topic.pms: burraq.product-media-service.media_specifications
         topic.psss: product-specifications-status-service
         topic.pmss: product-media-status-service
         topic.pos: burraq.product-offering-service.offering_details
         topic.ls: burraq.locale-service.locales
      group-id: export-aggregation-service
info:
  version: ${project.version}
management:
  endpoint:
    shutdown:
      enabled: true
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      # Eureka server address
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    
---
spring:
  profiles: dev
  data:
    dynamodb:
      read-capacity-units: 1
      write-capacity-units: 1
      access-key: dev-access-key
      secret-key: dev-secret-key
      ddl:
        enabled: false
      # https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/regions/Regions.html
      regions: US_EAST_2

---
spring:
  profiles: docker
  data:
    dynamodb:
      read-capacity-units: 1
      write-capacity-units: 1
      access-key: dev-access-key
      secret-key: dev-secret-key
      ddl:
        enabled: false
      # https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/regions/Regions.html
      regions: US_EAST_2
      
---
spring:
  data:
    elasticsearch:
      node: http://localhost:9200
      protocol: http
      service-name: none
      region: none
      
---
feign:
   client:
     config:
       retry:
         period: 1000
         maxPeriod: 1000
         maxAttempts: 3
     default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: basic      

   