spring:
  application:
    name: export-aggregation-service
  profiles:
    active: dev
info:
  version: ${project.version}
management:
  endpoint:
    shutdown:
      enabled: true
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      # Eureka server address
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

---
spring:
  profiles: dev

---
spring:
  profiles: docker
