spring:
  application:
    name: export-aggregation-service
  profiles:
    active: dev
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      properties:
         schema.registry.url: http://localhost:8081
         topic.pspecs: burraq.product-specifications-service.specifications
         topic.tas: translation-service
         topic.bacs: barcode-service
         topic.pcs: product-code-service
         topic.pas: product-accessory-service
         topic.pms: product-media-service
      group-id: export-aggregation-service
info:
  version: ${project.version}
management:
  endpoint:
    shutdown:
      enabled: true
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      # Eureka server address
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    
---
spring:
  profiles: dev
  data:
    dynamodb:
      read-capacity-units: 1
      write-capacity-units: 1
      access-key: dev-access-key
      secret-key: dev-secret-key
      ddl:
        enabled: true
      # https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/regions/Regions.html
      regions: US_EAST_2
      timeout: 60000

---
spring:
  profiles: docker
  data:
    dynamodb:
      read-capacity-units: 1
      write-capacity-units: 1
      access-key: dev-access-key
      secret-key: dev-secret-key
      ddl:
        enabled: true
      # https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/regions/Regions.html
      regions: US_EAST_2
      timeout: 60000
