spring:
  application:
    name: export-aggregation-service
  profiles:
    active: dev
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      properties:
         schema.registry.url: http://localhost:8081
      group-id: product-specifications-search-service
      auto-offset-reset: earliest
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
info:
  version: ${project.version}
management:
  endpoint:
    shutdown:
      enabled: true
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      # Eureka server address
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    
---
kafka:
  topic:
    pspecs: burraq.product-specifications-service.specifications

---
spring:
  profiles: dev

---
spring:
  profiles: docker
