/*
 * #region
 * export-aggregation-service
 * %%
 * Copyright (C) 2018 - 2019 Etilize
 * %%
 * NOTICE: All information contained herein is, and remains the property of ETILIZE.
 * The intellectual and technical concepts contained herein are proprietary to
 * ETILIZE and may be covered by U.S. and Foreign Patents, patents in process, and
 * are protected by trade secret or copyright law. Dissemination of this information
 * or reproduction of this material is strictly forbidden unless prior written
 * permission is obtained from ETILIZE. Access to the source code contained herein
 * is hereby forbidden to anyone except current ETILIZE employees, managers or
 * contractors who have executed Confidentiality and Non-disclosure agreements
 * explicitly covering such access.
 *
 * The copyright notice above does not evidence any actual or intended publication
 * or disclosure of this source code, which includes information that is confidential
 * and/or proprietary, and is a trade secret, of ETILIZE. ANY REPRODUCTION, MODIFICATION,
 * DISTRIBUTION, PUBLIC PERFORMANCE, OR PUBLIC DISPLAY OF OR THROUGH USE OF THIS
 * SOURCE CODE WITHOUT THE EXPRESS WRITTEN CONSENT OF ETILIZE IS STRICTLY PROHIBITED,
 * AND IN VIOLATION OF APPLICABLE LAWS AND INTERNATIONAL TREATIES. THE RECEIPT
 * OR POSSESSION OF THIS SOURCE CODE AND/OR RELATED INFORMATION DOES NOT CONVEY OR
 * IMPLY ANY RIGHTS TO REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS, OR TO
 * MANUFACTURE, USE, OR SELL ANYTHING THAT IT MAY DESCRIBE, IN WHOLE OR IN PART.
 * #endregion
 */

package com.etilize.burraq.eas.media.status;

import static com.etilize.burraq.eas.kafka.redis.KafkaConnectRedisMessageProperties.*;
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;

import java.util.Optional;

import org.junit.Test;

import com.etilize.burraq.eas.kafka.redis.KafkaConnectRedisMessagesDecoder;
import com.etilize.burraq.eas.kafka.redis.PSSSUpsertMessagePayload;
import com.etilize.burraq.eas.test.AbstractIntegrationTest;

/**
 * Functional tests for {@link KafkaConnectRedisMessagesDecoderTest}
 *
 * @author Affan Hasan
 * @since 1.0
 */
public class KafkaConnectRedisMessagesDecoderTest extends AbstractIntegrationTest {

    private final KafkaConnectRedisMessagesDecoder kafkaConnectRedisMessageDecoder = new KafkaConnectRedisMessagesDecoder();

    @Test
    public void shouldGetSpecificationLocalesFromHMSetCommandForCreateSpecificationStatuses() {
        final String base64EncodedMessagePayload = "{\"key\":\"cHJvZHVjdF9zdGF0dXNlczpwcm9kdWN0MTIz\",\"fields\":{\"ZW5fVVM=\":\"TkVX\",\"aWQ=\":\"cHJvZHVjdDEyMw==\",\"X2NsYXNz\":\"Y29tLmV0aWxpemUuYnVycmFxLnBzc3MucHJvZHVjdHN0YXR1cy5Qcm9kdWN0U3RhdHVz\"}}";
        final Optional<PSSSUpsertMessagePayload> payload = kafkaConnectRedisMessageDecoder.convertJsonToProductSpecificationsStatusUpsertMessagePayload(
                base64EncodedMessagePayload);
        final PSSSUpsertMessagePayload productSpecificationsStatusMessagePayload = payload.get();
        assertThat(productSpecificationsStatusMessagePayload.getKey(),
                is("product_statuses:product123"));
        assertThat(productSpecificationsStatusMessagePayload.getFields() //
                .size(), is(2));
        assertThat(productSpecificationsStatusMessagePayload.getFields() //
                .get("en_US"), is("NEW"));
        assertThat(productSpecificationsStatusMessagePayload.getFields() //
                .get(ID), is("product123"));
    }

    /**
     * The message generated by redis-connector in PSSS contains all locale values when a new specification locale is added to a product.
     *
     * Because in PSSS upon adding a new locale the product is deleted first and then recreated with new & previous locale values.
     */
    @Test
    public void shouldGetSpecificationLocalesFromHMSetCommandForAddNewSpecificationStatus() {
        final String base64EncodedMessagePayload = "{\"key\":\"cHJvZHVjdF9zdGF0dXNlczpwcm9kdWN0MTIz\",\"fields\":{\"aWQ=\":\"cHJvZHVjdDEyMw==\",\"X2NsYXNz\":\"Y29tLmV0aWxpemUuYnVycmFxLnBzc3MucHJvZHVjdHN0YXR1cy5Qcm9kdWN0U3RhdHVz\",\"ZW5fVUs=\":\"TkVX\", \"ZW5fVVM=\":\"TkVX\"}}";
        final Optional<PSSSUpsertMessagePayload> payload = kafkaConnectRedisMessageDecoder.convertJsonToProductSpecificationsStatusUpsertMessagePayload(
                base64EncodedMessagePayload);
        final PSSSUpsertMessagePayload productSpecificationsStatusMessagePayload = payload.get();
        assertThat(productSpecificationsStatusMessagePayload.getKey(),
                is("product_statuses:product123"));
        assertThat(productSpecificationsStatusMessagePayload.getFields() //
                .size(), is(3));
        assertThat(productSpecificationsStatusMessagePayload.getFields() //
                .get("en_UK"), is("NEW"));
        assertThat(productSpecificationsStatusMessagePayload.getFields() //
                .get("en_US"), is("NEW"));
        assertThat(productSpecificationsStatusMessagePayload.getFields() //
                .get(ID), is("product123"));
    }

    @Test
    public void shouldReturnEmptyWhenMessageIsNotForProductSpecificationStatuses() {
        final String base64EncodedMessagePayloadForStatuses = "{\"key\":\"c3RhdHVzZXM6Tk9UX0ZPVU5E\",\"fields\":{\"X2NsYXNz\":\"Y29tLmV0aWxpemUuYnVycmFxLnBzc3Muc3RhdHVzLlN0YXR1cw==\",\"aWQ=\":\"Tk9UX0ZPVU5E\",\"bmFtZQ==\":\"Tm90IEZvdW5k\",\"ZGVzY3JpcHRpb24=\":\"UHJvZHVjdCBpcyBub3QgZm91bmQ=\",\"Z3JvdXA=\":\"SVNTVUU=\"}}";
        final Optional<PSSSUpsertMessagePayload> productSpecificationsStatusMessagePayload = kafkaConnectRedisMessageDecoder.convertJsonToProductSpecificationsStatusUpsertMessagePayload(
                base64EncodedMessagePayloadForStatuses);
        assertThat(productSpecificationsStatusMessagePayload.isPresent(), is(false));
    }

    @Test
    public void shouldGetProductIdToDeleteAllSpecificationsStatuses() {
        final String base64EncodedMessagePayload = "{\"key\":\"cHJvZHVjdF9zdGF0dXNlcw==\",\"members\":[\"cHJvZHVjdDEyMw==\"]}";
        final Optional<String> productId = kafkaConnectRedisMessageDecoder.extractProductIdFromDeleteSpecificationsStatusesMessage(
                base64EncodedMessagePayload);
        assertThat(productId.isPresent(), is(true));
        assertThat(productId.get(), is("product123"));
    }
}
